### PR TITLE
finished troubleshoot script

### PR DESCRIPTION
**Pull request by namila007**
you can find the readme here [README.md](https://github.com/namila007/Pera_WiFi_Fixer)

### CODE REVIEW

**Review by kasvith — COMMENTED** [review]
What are strange characters in the script ?

**Comment by namila007** [comment]
What??

**Comment by kasvith** [comment]
Wait until i test

**Comment by namila007** [comment]
ok 💃

**Comment by kasvith** [comment]
Found these errors in script

> kasun@KASUN-INSPIRON-:/mnt/f/Projects/pera-wifi-easy$ ./test 
> ./test: line 2: $'\r': command not found                     
> ./test: line 4: $'\r': command not found                     
> ./test: line 8: $'\r': command not found                     
> ./test: line 16: syntax error near unexpected token `$'{\r'' 
> '/test: line 16: `set_dl(){

**Comment by namila007** [comment]
fixed

**Comment by kasvith** [comment]
Follow a syntax style and update code

**Comment by namila007** [comment]
done

**Pull request merged**
